@startuml
'https://plantuml.com/sequence-diagram
hide footbox

box
participant ":StartCommand" as StartCommand
participant ":TimeLimitMode" as TimeLimitMode
participant ":ClockThread" as ClockThread
participant ":Ui" as Ui
participant ":BufferedReader" as BufferedReader
participant ":DifficultyLevel" as DifficultyLevel

StartCommand -> TimeLimitMode: startTimeLimitMode(testText, difficulty)
activate TimeLimitMode
TimeLimitMode -> Ui: showTimeLimitModeInstructions()
loop for each line in testText
    TimeLimitMode -> ClockThread: start()
    TimeLimitMode -> Ui: Display text
    TimeLimitMode -> DifficultyLevel: getTimeLimit(text, difficulty)
    TimeLimitMode -> BufferedReader: waitForInput(clockThread, reader, timeLimit)
    alt User types within time limit
        BufferedReader -> TimeLimitMode: return user input
        TimeLimitMode -> Ui: Show "Great!" or "Wrong!"

    else Time runs out
        TimeLimitMode -> Ui: Show "Time's up!"
    end
    TimeLimitMode -> ClockThread: interrupt()
end
TimeLimitMode -> Ui: Show result

end box
@enduml