@startuml
'https://plantuml.com/sequence-diagram
hide footbox

box
participant ":StartCommand" as StartCommand
participant ":NormalMode" as NormalMode
participant ":Ui" as Ui
participant ":Scanner" as Scanner
participant ":TypingAccuracy" as TypingAccuracy
participant ":TypingTargetList" as TypingTargetList
participant ":TypingTargets" as TypingTargets
participant ":AutoAdjust" as AutoAdjust
participant ":State" as State

StartCommand -> NormalMode : startNormalMode(testText)
activate NormalMode
NormalMode -> TypingAccuracy : setTestText(testText)
NormalMode -> Ui : showStartGame()

loop for each line in testText
    NormalMode -> Ui : Display text
    NormalMode -> Scanner : nextLine()
    activate "Scanner"
    Scanner --> NormalMode : userInput
    deactivate "Scanner"
    NormalMode -> TypingAccuracy : updateUserInput(userInput)
end

NormalMode -> Ui : Show result

loop for each TypingTargets in typingTargetList
    NormalMode -> TypingTargets : check target
    TypingTargets --> NormalMode : result
end

NormalMode -> TypingTargets : update(typingTargetList)
NormalMode -> AutoAdjust : evaluate(wordCount/duration)

alt updateHighScore succeeds
    NormalMode -> State : updateHighScore(typingAccuracy, typingSpeedWPM)
else IOException occurs
    NormalMode -> Ui : showErrorMessage(e.getMessage())
end

end box



@enduml
