@startuml
hide circle
skinparam classAttributeIconSize 0

class Storage {
    - <u>data: ArrayList<Double>
    - file: File
    + saveScoreList(ArrayList<Double>)
    + readHighScoreList()
}

class State {
    - storage: storage
    - highScoreList: ArrayList<Double>
    - <u>df: DecimalFormat
    + getHighScore()
    + getHighScoreList()
    + updateHighScore(Double, int)
}

State --> Storage
@enduml
