@startuml
hide footbox
participant ":TypingAccuracyCommand" as TypingAccuracyCommand
participant ":TypingAccuracy" as TypingAccuracy
participant ":BoboTypeException" as BoboTypeException

TypingAccuracyCommand -> TypingAccuracy : new TypingAccuracy(userText)
activate TypingAccuracy
TypingAccuracy -> TypingAccuracy ++: setTestText(testText)
return testText
TypingAccuracy -> TypingAccuracy ++ : updateUserInput(userInput)
return userInput
TypingAccuracyCommand -> TypingAccuracy ++ : getTypingAccuracy()


opt testText is null
    TypingAccuracy -> BoboTypeException : throw new BoboTypeException()
end

TypingAccuracy --> TypingAccuracyCommand

deactivate TypingAccuracy
@enduml