@startuml
'https://plantuml.com/sequence-diagram
hide footbox


box
participant ":StartCommand" as StartCommand
participant ":ZenMode" as ZenMode
participant ":TypingTimer" as TypingTimer
participant ":Ui" as Ui

StartCommand -> ZenMode
activate ZenMode
ZenMode -> ZenMode: startZenMode()
ZenMode -> TypingTimer ++
return getTypingDuration()
ZenMode -> Ui ++ : showZenModeEndGame()

end box
@enduml